services:
  backend:
    build:
      context: .
    container_name: tagline-backend-dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/code/app
      - tagline-db-data:/data
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - DATABASE_URL=sqlite:////data/tagline.db
    env_file:
      - .env

volumes:
  tagline-db-data:
